config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'books/create'
  get 'books/show'
  get 'books/edit'
  get 'books/new'
  get 'books/update'
  get 'books/delete'
  resources :authors
  # get 'authors/index'
  # get 'authors/show'
  # get 'authors/new'
  # get 'authors/edit'
  # get 'authors/create'
  # get 'authors/update'
  # get 'authors/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
    @author.id = ""
  end

  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)
    @author.save
    redirect to "@author"
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_To @author
    else
      render 'edit'
    end
  end

  def delete
    @author = Author.find(params[:id])
    @author.destroy

    redirect_To authors_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all 
  end

  def create
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/delete.html.erb
<h1>Authors#delete</h1>
<p>Find me in app/views/authors/delete.html.erb</p>

app/views/authors/edit.html.erb
<h1>Edit Author on this page</h1>

<%= form_with(model: @author, local: true) do |form| %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<p> Click on link below to go back to home page </p>
<%= link_to 'Home', authors_path %>

app/views/authors/index.html.erb
<!-- <h1>Authors Homepage</h1>
<% @authors.each do |author| %>
  <div>
  <h2>Author Firstname:<%= author.first_name %></h2>
  <h2>Author Surname:<%= author.last_name %></p>
  <h2><% author.books.each do |books| %>
  <h2>Book Title:  <%= books.title %></h2>
  <h3>Book Page Number:<%= books.page_number %></h3>
  <h3>Book description:<%= books.description %></h3>

  <%end%>


  </div>
<% end %> -->



<h1>Authors Home Page</h1>
<% @authors.each do |author| %>
  <div>
  <hr>
  <h2>Name:<%= author.first_name %> <%= author.last_name %></h2>
  <h2><% author.books.each do |books| %>
  <h2>Book Title:  <%= books.title %></h2>
  <h3>Book Page Number:<%= books.page_number %></h3>
  <h3>Book description:<%= books.description %></h3>

  <% end %>
  <hr>
  <%= link_to 'Show', author_path(author) %>
  <%= link_to 'Edit', edit_author_path(author) %>
  <%= link_to 'Destroy', author_path(author) %>
  <%= link_to 'New', new_author_path %>
  </div>
<% end %>

app/views/authors/new.html.erb
<h1>Add New Book</h1>


<%= form_with scope: :article, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'index', authors_path %>

app/views/authors/show.html.erb
<h1>Authors show Page</h1>

<%= link_to 'Home', authors_path %> |
<%= link_to 'Edit', edit_author_path(@author) %>

<h1><%= @author.first_name %> <%= @author.last_name %></h1>
<

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/delete.html.erb
<h1>Books#delete</h1>
<p>Find me in app/views/books/delete.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksRelationships</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>